### ISSUE TITLE
Config issues - logger crash

### ISSUE THREAD

**Issue by loopyd** [GhostofGoes/sneaky-scripts#27]
C:\Users\lupin\Downloads\sneaky-scripts-master>sneaky --config sneaky-config.json
Traceback (most recent call last):
```
  File "C:\Python\Python27\Scripts\sneaky-script.py", line 11, in <module>
    load_entry_point('sneaky-scripts==0.3.1', 'console_scripts', 'sneaky')()
  File "C:\Python\Python27\lib\site-packages\sneaky_scripts-0.3.1-py2.7.egg\sneaky\sneaky_scripts.py", line 47, in main
    system = Windows(args)
  File "C:\Python\Python27\lib\site-packages\sneaky_scripts-0.3.1-py2.7.egg\sneaky\windows.py", line 18, in __init__
    BasePlatform.__init__(self, args)
  File "C:\Python\Python27\lib\site-packages\sneaky_scripts-0.3.1-py2.7.egg\sneaky\base_platform.py", line 21, in __init__
    self._log = logging.getLogger(self.__class__)
  File "C:\Python\Python27\lib\logging\__init__.py", line 1574, in getLogger
    return Logger.manager.getLogger(name)
  File "C:\Python\Python27\lib\logging\__init__.py", line 1038, in getLogger
    raise TypeError('A logger name must be string or Unicode')
TypeError: A logger name must be string or Unicode
```

Fix - MessageLogger

**Comment by GhostofGoes** [comment]
That fixes that, but there are other bugs. I haven't actually tested this since I rewrote as a package 😄
